### ISSUE TITLE
Training Loop 개선

### ISSUE THREAD

**Issue by YoojLee** [YoojLee/vit#3]
## 문제점
배치 사이즈를 256까지 줄임에도 불구하고 매우 느린 학습 속도. 30분 동안 하나의 step도 밟지 못함. 즉, 하나의 배치 사이즈도 처리를 못함.

## 예상되는 병목 지점
- dataset에서 패치 만들 때에 O(n^2)의 시간이 소요됨. 이러한 부분이 병목으로 예상됨.
- 애초에 데이터와 모델이 이전에 학습시켰던 것들보다 더 많아서 학습이 너무 느림.

## 해결안
- dataset에서 발생하는 병목은 ray를 활용해서 병렬처리
- 학습 속도 자체의 한계는 _"Better plain ViT baselines for ImageNet-1k"_를 바탕으로 모델 구조 개선을 수행할 예정.

## To-Do's
- [ ] num_threads 개수 조절해서 체크해보기
- [ ] generate_patches 부분 ray로 병렬처리
- [x] 아티클 읽고 모델 구조 개선
